# Generated by Django 2.2.1 on 2019-05-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_picture',
            field=models.ImageField(upload_to='store/images'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='store/images'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(upload_to='store/images'),
        ),
    ]
