# Generated by Django 2.2.1 on 2019-05-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_commodity_delete_flage'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='picture',
            field=models.ImageField(default='store/images/-426481924..jpg', upload_to='store/images'),
        ),
    ]
